import { Inter } from 'next/font/google'

import '../src/styles/index.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Readme Generator',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
